### PR TITLE
Support audio streaming over CAT of (tr)uSDX

### PR DESCRIPTION
**Pull request by d3m3vilurr**
same as #61 
just rebased with `Dev` branch

### CODE REVIEW

**Comment by N0BOY** [comment]
@d3m3vilurr minor fix of MainViewModel. Please test on your (tr)uSDX.

Thanks for the PR.

**Comment by d3m3vilurr** [comment]
@N0BOY Hi. I read your partial revert patch of the https://github.com/N0BOY/FT8CN/pull/67/commits/8f5975b107166f2

trusdx's audio stream over CAT is not made a audio channel.
it only uses the CAT serial channel.
it mean, we cannot receive/transmit the sound via mic/speaker lines.
so I'll expect that the patch wouldn't work well if an app flow doesn't changes between 0.89 and 0.90.

so, this [setDataFromLan](https://github.com/N0BOY/FT8CN/commit/ffed0a8898786a6430552163594a96d3f6a293c2#diff-27caf546c9a904bed4fd6f747383e04d10860f58abd650e6e812b78d05b0211dL825-L829) is wrong name now.
it could be changed to `setDataFromLanOrDataCable`
samely that this is reason of why I add [onTransmitOverCAT](https://github.com/N0BOY/FT8CN/commit/ffed0a8898786a6430552163594a96d3f6a293c2#diff-27caf546c9a904bed4fd6f747383e04d10860f58abd650e6e812b78d05b0211dL428-L436)

but, I'll test/share the result tonight, :)

**Comment by d3m3vilurr** [comment]
it has multiple compile errors.
but i think you want to revert/clean up my dirty patches :)
so i [removed that my patch things](https://github.com/d3m3vilurr/FT8CN/commit/c936ed2300ca26966bc) which raised an error at the compile time.

expect result:
- phone sound cannot make any effect to TX signal.
- generated TX transmit signal can see on the another rig
- we can see correct RX spectrum from rig
- MIC of phone cannot make any happen to the spectrum

testing result:
all tests failed after the revert patch

**Comment by N0BOY** [comment]
Hi Sunguk, there was some miscommunication between me and YOZ, when pushing out [ffed0a8](https://github.com/N0BOY/FT8CN/commit/ffed0a8898786a6430552163594a96d3f6a293c2).

Please try again with [069205d](https://github.com/N0BOY/FT8CN/commit/069205d44a9355b8667b725a50c3f96f765a9ed1), and see if you can at least compile it.

**Comment by d3m3vilurr** [comment]
@N0BOY It seems to work well. and also I couldn't find any problem in the patch code.

TX/RX is good and I made one QSO.

TY & 73 DE DS1UFX

**Comment by N0BOY** [comment]
Sounds good! However, @BG7YOZ already started the v0.91 revision before this merge. We may need to do another round of code review when have the next stable release candidate.

**Pull request merged**
